In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# machine learning libs
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline 

#from sklearn.compose import ColumnTransformer, make_column_selector
#from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer, StandardScaler
from sklearn import config_context
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
df = pd.read_csv("Documents/tree_based_ML_features_final.csv")
df

#data frame of just iphone 13

print(df[(df['phone_generation']==13)&(df['claim']<=500)])

      phone_generation  phone_size  week_of_year  month  quarter  year  \
6124                13         128            48     11        4  2021
6125                13         128            50     12        4  2021
6126                13         128            51     12        4  2021
6127                13         128            52     12        4  2021
6128                13         128             1      1        1  2022
...                ...         ...           ...    ...      ...   ...
7743                13         512             2      1        1  2023
7744                13         512             3      1        1  2023
7745                13         512             4      1        1  2023
7746                13         512             5      1        1  2023
7747                13         512             6      2        1  2023

      holiday  days_since_release_date  claim  black  ...  apple iphone 6s  \
6124        0                       36      2      0  ...                0
6125        0                       50      2      0  ...                0
6126        1                       57      1      0  ...                0
6127        0                       64      9      0  ...                0
6128        0                       71      3      0  ...                0
...       ...                      ...    ...    ...  ...              ...
7743        0                      442      4      0  ...                0
7744        0                      449      1      0  ...                0
7745        0                      456      2      0  ...                0
7746        0                      463      8      0  ...                0
7747        0                      470     14      0  ...                0

      apple iphone 6s plus  apple iphone 7  apple iphone 7 plus  \
6124                     0               0                    0
6125                     0               0                    0
6126                     0               0                    0
6127                     0               0                    0
6128                     0               0                    0
...                    ...             ...                  ...
7743                     0               0                    0
7744                     0               0                    0
7745                     0               0                    0
7746                     0               0                    0
7747                     0               0                    0

      apple iphone 8  apple iphone 8 plus  apple iphone x  apple iphone xr  \
6124               0                    0               0                0
6125               0                    0               0                0
6126               0                    0               0                0
6127               0                    0               0                0
6128               0                    0               0                0
...              ...                  ...             ...              ...
7743               0                    0               0                0
7744               0                    0               0                0
7745               0                    0               0                0
7746               0                    0               0                0
7747               0                    0               0                0

      apple iphone xs  apple iphone xs max
6124                0                    0
6125                0                    0
6126                0                    0
6127                0                    0
6128                0                    0
...               ...                  ...
7743                0                    0
7744                0                    0
7745                0                    0
7746                0                    0
7747                0                    0

[1624 rows x 55 columns]

In [40]:
#55 total
df.shape

(16579, 55)

In [41]:
df=df[['phone_generation','phone_size','week_of_year', 'month', 'quarter',
       'year', 'days_since_release_date', 'holiday','claim', 'black', 'blue',
       'coral', 'gold', 'graphite', 'gray', 'green', 'midnight', 'pink',
       'purple', 'red', 'silver', 'starlight', 'white', 'yellow']]

In [42]:
#only looking at these generations rather than the specific models for an iphone like pro, max, etc. because we are only looking to predict iphone 14
df['phone_generation'].unique()

array([11, 12, 13, 14,  3,  4,  5,  6,  7,  8, 10])

In [62]:
#split the data into train and test sets
from sklearn.model_selection import train_test_split

feature_selection = df.columns.to_list()
feature_selection.remove('claim')
feature_selection = df[feature_selection]

train_data = df[(df['phone_generation']==13)& (df['days_since_release_date'] <= 160)]
train_data=train_data[['days_since_release_date','phone_size','holiday','claim', 'black', 'blue',
       'coral', 'gold', 'graphite', 'gray', 'green', 'midnight', 'pink',
       'purple', 'red', 'silver', 'starlight', 'white', 'yellow']]
x_train= train_data.drop('claim', axis=1)
y_train = train_data['claim']

#val_data=df[(df['phone_generation'] == 13) & (df['days_since_release_date'] >=414) & (df['days_since_release_date'] <=470)]
#val_data=val_data[['days_since_release_date','phone_size','holiday','claim', 'black', 'blue',
       #'coral', 'gold', 'graphite', 'gray', 'green', 'midnight', 'pink',
       #'purple', 'red', 'silver', 'starlight', 'white', 'yellow']]
#x_val= val_data.drop('claim', axis=1)
#y_val = val_data['claim']

test_data=df[(df['phone_generation']==14) & (df['year'] >= 2023 ) & (df['month']==2) ]
test_data=test_data[['days_since_release_date','phone_size','holiday','claim', 'black', 'blue',
       'coral', 'gold', 'graphite', 'gray', 'green', 'midnight', 'pink',
       'purple', 'red', 'silver', 'starlight', 'white', 'yellow']]


features = test_data.drop('claim', axis=1)
target = test_data['claim']

In [63]:
print(train_data)

      days_since_release_date  phone_size  holiday  claim  black  blue  coral  \
6124                       36         128        0      2      0     1      0
6125                       50         128        0      2      0     1      0
6126                       57         128        1      1      0     1      0
6127                       64         128        0      9      0     1      0
6128                       71         128        0      3      0     1      0
...                       ...         ...      ...    ...    ...   ...    ...
7586                      127         256        0     13      0     0      0
7587                      134         256        0     10      0     0      0
7588                      141         256        0     13      0     0      0
7589                      148         256        0     16      0     0      0
7590                      155         256        0     10      0     0      0

      gold  graphite  gray  green  midnight  pink  purple  red  silver  \
6124     0         0     0      0         0     0       0    0       0
6125     0         0     0      0         0     0       0    0       0
6126     0         0     0      0         0     0       0    0       0
6127     0         0     0      0         0     0       0    0       0
6128     0         0     0      0         0     0       0    0       0
...    ...       ...   ...    ...       ...   ...     ...  ...     ...
7586     0         0     0      0         0     0       0    0       1
7587     0         0     0      0         0     0       0    0       1
7588     0         0     0      0         0     0       0    0       1
7589     0         0     0      0         0     0       0    0       1
7590     0         0     0      0         0     0       0    0       1

      starlight  white  yellow
6124          0      0       0
6125          0      0       0
6126          0      0       0
6127          0      0       0
6128          0      0       0
...         ...    ...     ...
7586          0      0       0
7587          0      0       0
7588          0      0       0
7589          0      0       0
7590          0      0       0

[73 rows x 19 columns]

In [64]:
print(features)

      days_since_release_date  phone_size  holiday  black  blue  coral  gold  \
7760                      143         128        0      1     0      0     0
7773                      143         128        0      0     0      0     0
7785                      143         256        0      1     0      0     0
7802                      143         256        0      0     0      0     0
7805                      143         512        0      1     0      0     0
7806                      143         512        0      0     0      0     0
7807                      143         128        0      1     0      0     0
7808                      143         128        0      0     0      0     1
7809                      143         128        0      0     0      0     0
7810                      143         128        0      0     0      0     0

      graphite  gray  green  midnight  pink  purple  red  silver  starlight  \
7760         0     0      0         0     0       0    0       0          0
7773         0     0      0         0     0       0    0       0          0
7785         0     0      0         0     0       0    0       0          0
7802         0     0      0         0     0       0    0       0          0
7805         0     0      0         0     0       0    0       0          0
7806         0     0      0         0     0       0    0       0          0
7807         0     0      0         0     0       0    0       0          0
7808         0     0      0         0     0       0    0       0          0
7809         0     0      0         0     0       1    0       0          0
7810         0     0      0         0     0       0    0       1          0

      white  yellow
7760      0       0
7773      1       0
7785      0       0
7802      1       0
7805      0       0
7806      1       0
7807      0       0
7808      0       0
7809      0       0
7810      0       0

In [65]:
#target is the claim value
print(target)

7760    31
7773    12
7785    11
7802     5
7805     1
7806     1
7807    71
7808    50
7809    68
7810     1
Name: claim, dtype: int64

In [66]:
# x train
print('On X train: ')
print('X train dimensions: ', x_train.shape)
display(x_train.head())
# x test
print('\nOn X test: ')
print('X test dimensions: ', x_test.shape)
display(x_test.head())

On X train:
X train dimensions:  (73, 18)

,days_since_release_date,phone_size,holiday,black,blue,coral,gold,graphite,gray,green,midnight,pink,purple,red,silver,starlight,white,yellow
6124,36,128,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6125,50,128,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6126,57,128,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6127,64,128,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6128,71,128,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

On X test:
X test dimensions:  (26, 18)

,days_since_release_date,phone_size,holiday,black,blue,coral,gold,graphite,gray,green,midnight,pink,purple,red,silver,starlight,white,yellow
7755,108,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7756,115,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7757,122,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7758,129,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7759,136,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [67]:
# y train
print('On y train: ')
print('y train dimensions: ', y_train.shape)
display(y_train.head())

# y test
print('\nOn y test: ')
print('y test dimensions: ', y_test.shape)
display(y_test.head())

On y train:
y train dimensions:  (73,)

6124    2
6125    2
6126    1
6127    9
6128    3
Name: claim, dtype: int64

On y test:
y test dimensions:  (26,)

7755    28
7756    37
7757    35
7758    39
7759    33
Name: claim, dtype: int64

In [68]:
np.unique(y_train)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  19,  21,  22,  23,  24,  30,  31,  32,  35,  40,
        41,  43,  55,  56,  57,  61,  66,  69,  70,  71,  78,  83,  91,
        93,  95, 105, 127])

In [69]:
np.unique(x_train)

array([  0,   1,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,  92,
        99, 106, 113, 120, 127, 128, 134, 141, 148, 155, 256])

#XGBoost

In [70]:
!pip install xgboost

Requirement already satisfied: xgboost in ./opt/anaconda3/lib/python3.9/site-packages (1.7.5)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in ./opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)

In [71]:
#model with no training data

import xgboost as xgb
model=xgb.XGBRegressor()
model=model.fit(x_train, y_train, eval_set=[(x_train, y_train), (x_val, y_val)])

pred_claim=model.predict(features)

[0]	validation_0-rmse:29.79117	validation_1-rmse:132.22529
[1]	validation_0-rmse:23.18322	validation_1-rmse:126.08460
[2]	validation_0-rmse:18.32819	validation_1-rmse:121.56383
[3]	validation_0-rmse:14.60309	validation_1-rmse:117.31858
[4]	validation_0-rmse:11.87017	validation_1-rmse:114.31432
[5]	validation_0-rmse:9.50770	validation_1-rmse:111.16963
[6]	validation_0-rmse:7.90816	validation_1-rmse:109.15510
[7]	validation_0-rmse:6.69392	validation_1-rmse:107.62231
[8]	validation_0-rmse:5.63266	validation_1-rmse:106.64794
[9]	validation_0-rmse:4.66763	validation_1-rmse:106.01137
[10]	validation_0-rmse:3.96424	validation_1-rmse:105.48545
[11]	validation_0-rmse:3.41074	validation_1-rmse:105.06352
[12]	validation_0-rmse:2.89121	validation_1-rmse:104.73866
[13]	validation_0-rmse:2.51292	validation_1-rmse:104.50301
[14]	validation_0-rmse:2.21366	validation_1-rmse:104.30786
[15]	validation_0-rmse:1.94412	validation_1-rmse:104.14572
[16]	validation_0-rmse:1.72494	validation_1-rmse:104.01062
[17]	validation_0-rmse:1.55357	validation_1-rmse:103.89775
[18]	validation_0-rmse:1.42212	validation_1-rmse:103.80324
[19]	validation_0-rmse:1.29372	validation_1-rmse:103.72394
[20]	validation_0-rmse:1.17572	validation_1-rmse:103.65729
[21]	validation_0-rmse:1.07150	validation_1-rmse:103.60117
[22]	validation_0-rmse:1.00588	validation_1-rmse:103.55387
[23]	validation_0-rmse:0.93129	validation_1-rmse:103.51394
[24]	validation_0-rmse:0.89997	validation_1-rmse:103.48021
[25]	validation_0-rmse:0.81856	validation_1-rmse:103.45169
[26]	validation_0-rmse:0.79065	validation_1-rmse:103.42755
[27]	validation_0-rmse:0.77507	validation_1-rmse:103.40711
[28]	validation_0-rmse:0.74750	validation_1-rmse:103.38980
[29]	validation_0-rmse:0.73764	validation_1-rmse:103.37512
[30]	validation_0-rmse:0.66657	validation_1-rmse:103.36267
[31]	validation_0-rmse:0.63325	validation_1-rmse:103.35211
[32]	validation_0-rmse:0.62653	validation_1-rmse:103.34315
[33]	validation_0-rmse:0.62164	validation_1-rmse:103.33555
[34]	validation_0-rmse:0.60595	validation_1-rmse:103.32909
[35]	validation_0-rmse:0.58828	validation_1-rmse:103.32361
[36]	validation_0-rmse:0.57525	validation_1-rmse:103.31895
[37]	validation_0-rmse:0.56290	validation_1-rmse:103.31500
[38]	validation_0-rmse:0.48695	validation_1-rmse:103.31164
[39]	validation_0-rmse:0.44062	validation_1-rmse:103.30472
[40]	validation_0-rmse:0.42701	validation_1-rmse:103.30161
[41]	validation_0-rmse:0.41578	validation_1-rmse:103.29951
[42]	validation_0-rmse:0.40357	validation_1-rmse:103.30001
[43]	validation_0-rmse:0.39969	validation_1-rmse:103.29722
[44]	validation_0-rmse:0.35701	validation_1-rmse:103.29546
[45]	validation_0-rmse:0.35533	validation_1-rmse:103.29542
[46]	validation_0-rmse:0.35232	validation_1-rmse:103.29268
[47]	validation_0-rmse:0.35038	validation_1-rmse:103.29540
[48]	validation_0-rmse:0.34826	validation_1-rmse:103.29439
[49]	validation_0-rmse:0.31834	validation_1-rmse:103.29327
[50]	validation_0-rmse:0.28797	validation_1-rmse:103.29233
[51]	validation_0-rmse:0.25985	validation_1-rmse:103.29106
[52]	validation_0-rmse:0.23912	validation_1-rmse:103.29009
[53]	validation_0-rmse:0.23762	validation_1-rmse:103.28972
[54]	validation_0-rmse:0.23306	validation_1-rmse:103.28952
[55]	validation_0-rmse:0.23018	validation_1-rmse:103.28887
[56]	validation_0-rmse:0.22951	validation_1-rmse:103.28934
[57]	validation_0-rmse:0.21057	validation_1-rmse:103.28898
[58]	validation_0-rmse:0.21036	validation_1-rmse:103.28907
[59]	validation_0-rmse:0.17813	validation_1-rmse:103.28880
[60]	validation_0-rmse:0.15334	validation_1-rmse:103.28864
[61]	validation_0-rmse:0.13353	validation_1-rmse:103.28762
[62]	validation_0-rmse:0.11642	validation_1-rmse:103.28601
[63]	validation_0-rmse:0.10317	validation_1-rmse:103.28660
[64]	validation_0-rmse:0.09242	validation_1-rmse:103.28595
[65]	validation_0-rmse:0.08456	validation_1-rmse:103.28648
[66]	validation_0-rmse:0.08066	validation_1-rmse:103.28656
[67]	validation_0-rmse:0.07529	validation_1-rmse:103.28701
[68]	validation_0-rmse:0.07448	validation_1-rmse:103.28713
[69]	validation_0-rmse:0.07395	validation_1-rmse:103.28704
[70]	validation_0-rmse:0.06644	validation_1-rmse:103.28652
[71]	validation_0-rmse:0.06612	validation_1-rmse:103.28636
[72]	validation_0-rmse:0.06048	validation_1-rmse:103.28612
[73]	validation_0-rmse:0.06019	validation_1-rmse:103.28618
[74]	validation_0-rmse:0.05550	validation_1-rmse:103.28581
[75]	validation_0-rmse:0.05329	validation_1-rmse:103.28658
[76]	validation_0-rmse:0.05111	validation_1-rmse:103.28670
[77]	validation_0-rmse:0.05062	validation_1-rmse:103.28639
[78]	validation_0-rmse:0.04941	validation_1-rmse:103.28709
[79]	validation_0-rmse:0.04860	validation_1-rmse:103.28720
[80]	validation_0-rmse:0.04842	validation_1-rmse:103.28706
[81]	validation_0-rmse:0.04767	validation_1-rmse:103.28711
[82]	validation_0-rmse:0.04753	validation_1-rmse:103.28713
[83]	validation_0-rmse:0.04712	validation_1-rmse:103.28695
[84]	validation_0-rmse:0.04705	validation_1-rmse:103.28699
[85]	validation_0-rmse:0.04626	validation_1-rmse:103.28697
[86]	validation_0-rmse:0.04610	validation_1-rmse:103.28709
[87]	validation_0-rmse:0.04595	validation_1-rmse:103.28689
[88]	validation_0-rmse:0.04584	validation_1-rmse:103.28696
[89]	validation_0-rmse:0.04580	validation_1-rmse:103.28697
[90]	validation_0-rmse:0.04577	validation_1-rmse:103.28697
[91]	validation_0-rmse:0.04514	validation_1-rmse:103.28760
[92]	validation_0-rmse:0.04277	validation_1-rmse:103.28778
[93]	validation_0-rmse:0.04162	validation_1-rmse:103.28779
[94]	validation_0-rmse:0.04137	validation_1-rmse:103.28781
[95]	validation_0-rmse:0.03570	validation_1-rmse:103.28800
[96]	validation_0-rmse:0.03456	validation_1-rmse:103.28813
[97]	validation_0-rmse:0.03380	validation_1-rmse:103.28800
[98]	validation_0-rmse:0.03193	validation_1-rmse:103.28772
[99]	validation_0-rmse:0.03063	validation_1-rmse:103.28749

In [72]:
def wmape(actual, forecast):
    # make a series called mape
    se_mape = abs(actual-forecast)/actual

    # get a float of the sum of the actual
    ft_actual_sum = actual.sum()

    # get a series of the multiple of the actual & the mape
    se_actual_prod_mape = actual * se_mape

    # summate the prod of the actual and the mape
    ft_actual_prod_mape_sum = se_actual_prod_mape.sum()

    # float: wmape of forecast
    ft_wmape_forecast = ft_actual_prod_mape_sum / ft_actual_sum

    # return a float
    return ft_wmape_forecast

In [73]:
wmape(target, pred_claim)

0.9882521097403598